New engine: Genius (lyrics)
searx/searx pull request #1004
Opened 2017-08-20 00:16 UTC by woorst

2017-08-20 22:01 UTC, dalf commented
The travis build shows some errors : 
```
/home/travis/build/asciimoo/searx/tests/unit/engines/test_genius.py:98:121: E501 line too long (125 > 120 characters)
/home/travis/build/asciimoo/searx/tests/unit/engines/test_genius.py:107:121: E501 line too long (127 > 120 characters)
/home/travis/build/asciimoo/searx/tests/unit/engines/test_genius.py:167:121: E501 line too long (122 > 120 characters)
```

you can run these tests on your machine using : 
```sh
./manage tests
```

see https://asciimoo.github.io/searx/dev/quickstart.html

2017-09-03 21:20 UTC, kvch commented
I am not sure if it is the fault of the engine or not, but the first few results shows the engine twice.
![genius-engine](https://user-images.githubusercontent.com/3876218/30006689-6d79dce6-90fe-11e7-84b8-6d673bc05cbd.png)

2017-09-03 21:21 UTC, kvch commented on searx/engines/genius.py
> +indicies = ['top_hit', 'song', 'lyric', 'artist', 'album', 'tag', 'video', 'article', 'user']
Why is this list here if it is not used anywhere?

2017-09-26 23:05 UTC, kvch requested changes
Please address the review notes.

2017-11-03 19:21 UTC, merged