Open Semantic Search Engine
searx/searx pull request #1321
Opened 2018-06-14 18:36 UTC by nicholasks

This new engine will be using Solr search server used by an Open Semantic Search setup.

This should close #1318 .

2018-06-15 10:03 UTC, Pofilo requested changes
base_url in configuration

2018-06-15 10:03 UTC, Pofilo commented on searx/engines/opensemantic.py
> +base_url = 'http://localhost:8983/solr/opensemanticsearch/'
Is this the classical URL given by an installation of Open Semantic Search ?
You should maybe put it in `settings.yml`. This way, the configuration is only done in the configuration file.
(So you can remove the comment maybe)

What do you think ?

2018-06-25 19:03 UTC, Pofilo approved these changes

2018-08-18 11:35 UTC, kvch commented on searx/settings.yml
> +  - name : opensemanticsearch
Engines which require action (installation, setting base_url) before being usable are usually commented out. See yacy as an example. Could you please comment it out?

2018-08-18 11:37 UTC, kvch commented on searx/engines/opensemantic.py
> +        item['originalData'] = current
Why is this needed? AFAIK `originalData` is not used anywhere.

2020-10-25 16:55 UTC, closed without merging