Add Gentoo wiki search engine
searx/searx pull request #1368
Opened 2018-08-12 10:49 UTC by aliceinwire

Add Gentoo wiki search engine

2018-08-18 11:04 UTC, kvch commented
Thanks for your contribution! Could you please address the issues detected by PEP8?

2018-08-19 02:28 UTC, aliceinwire commented
@kvch fixed pep8 issues

2018-08-21 10:47 UTC, asciimoo requested changes
Thanks for the PR. Please fix that one minor issue and it's ready to merge.

2018-08-21 10:47 UTC, asciimoo commented on searx/engines/gentoo.py
> +    print(language)
Please remove this debug print.

2018-08-21 13:56 UTC, aliceinwire commented on searx/engines/gentoo.py
> +    print(language)
fixed :)

2018-08-21 14:24 UTC, asciimoo approved these changes
Cool, thanks!

2018-08-21 14:24 UTC, merged