[fix] google play
searx/searx pull request #1612
Opened 2019-06-03 15:05 UTC by Venca24

fixes google play engines and adds thumbnails to their results

2019-06-03 17:48 UTC, kvch requested changes
I would rather extend the XPATH engine with thumbnail than to duplicate its code in a new engine.

2019-06-11 10:41 UTC, Venca24 commented
@kvch Is the test stuck?

2019-06-11 15:52 UTC, unixfox commented
probably because you need to rebase your branch with the master branch of searx.

2019-07-24 18:11 UTC, kvch approved these changes

2019-07-25 05:46 UTC, merged