Fix python 3.8 compatibility
searx/searx pull request #1745
Opened 2019-11-16 21:10 UTC by lorddavidiii

Archlinux has now python 3.8 and in pyhton 3.8 `escape` was removed from the `cgi` module, thus we need to import it from the `html` module.

2019-11-22 19:16 UTC, unixfox commented
Perfect! That's what I was looking for (I'm using Archlinux too).
@kvch @dalf Can you merge this PR?

2019-11-28 16:38 UTC, return42 requested changes

2019-11-28 16:38 UTC, return42 commented on searx/engines/framalibre.py
> +except:
[Zen](https://www.python.org/dev/peps/pep-0020/) - lets drop python V<3.5 compatibility.

2019-11-28 19:31 UTC, asciimoo approved these changes
Thanks!

2019-11-28 19:31 UTC, merged