Various fixes
searx/searx pull request #877
Opened 2017-03-16 18:46 UTC by dalf

2017-03-18 17:07 UTC, kvch commented
I tried to run again the Travis build to see if it was an environment problem, but the robot tests are still failing. Could you please take a look at it?

2017-03-18 22:38 UTC, dalf commented
This error : 
```
AssertionError: Setup failed:
WebDriverException: Message: Missing 'type' parameter
```
seems to appear in all new builds, see for example https://travis-ci.org/asciimoo/searx/builds/206807742 (A couple of fixes with search languages PR)  
 
Note : the commits are a messy (one is empty actually), sorry.

2017-04-08 15:45 UTC, asciimoo requested changes
Good fixes, thanks. Please modify the concatenation according to that one minor note

2017-04-08 15:45 UTC, asciimoo commented on searx/results.py
> +                + ':' + ('' if 'template' not in res else res['template'])\
this could be `':' + res.get('template', '')`

2017-05-22 19:20 UTC, dalf commented
ping ?

2017-05-22 20:20 UTC, asciimoo approved these changes
Sorry for the delay. Thanks.

2017-05-22 20:20 UTC, merged